[application]
name = "toki"
default_platform = "web"

[web.app]
title = "cryptonezumi.com"

[web.watcher]
watch_path = ["src", "assets", "public"]
index_on_404 = true



[bundle]
identifier = "com.cryptonezumi.toki"