[application]
name = "dioxus-app"
default_platform = "web"

[web.app]
title = "toki"

[bundle]
identifier = "cryptonezumi.app"

[web.watcher]
watch_path = ["src", "assets"]
index_on_404 = true

# Optional: Add extra CSS or JS files if needed
style = []
script = []

[web.resource.dev]
dev = true
