[application]
name = "dioxus-app"
default_platform = "web"

[web.app]
title = "toki"

[bundle]
identifier = "cryptonezumi.app"

[web.watcher]
watch_path = ["src", "assets", "public"]
index_on_404 = true

[web.resource]
style = []
script = []

[web.resource.dev]
dev = true